### PR TITLE
file test branch

### PR DESCRIPTION
**Pull request by wachirasenior0**
This pull request marks the three new features committed to the repositories. The features should include; 
index.html
style.css
test.md

### CODE REVIEW

**Review by jmonto55 — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES 🟡

Hi @wachirasenior0  👋🏽, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

AlmostThereGIF (2)







## Required Changes ♻️

- [ ] I noticed you created 3 different Pull Requests to implement steps for this Milestone, please kindly ensure to include all changes implemented for the Milestone using only 1 Pull Request next time. This time please continue using this PR for future reviews and implement all the changes required using this Pull Request too.
- [ ] Excellent job building your project 🚀. However, please kindly ensure to install and configure Linters for this project as requested in the requirements. 🤓 You can use [this link](https://github.com/microverseinc/linters-config/tree/master/html-css) for support on Linters configuration.
- [ ] Good work creating your `.gitignore` file ✔️. However, please kindly ensure to include the `test.md` file inside your `.gitignore` file as requested in the requirements. Currently, your `test.md` ism present in the repository. 🤓
- [ ] Please ensure to add a more meaningful name for your branch `feature3` does not give cluesa about the changes implemented in this Milestone. 🔧
- [ ] Great work building your pull request 💯. However, please kindly ensure to add a more meaningful title and description to your pull request birefly mentioning all the features implemented in this Milestone, check the image below to guide yourself on how to do this. 👇🏽

rq


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi  @wachirasenior0, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✅ You used the correct GitHub flow

 ## Required Changes ♻️
- First of all, :pray: Please before the request for a Review or Re-Review always make sure you have marked your PR as "Ready For Review". Check this [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) how to configure it.

- I really appreciate that you tried to implement a linter setup as the previous reviewer requested.  As I can see there is a typo in your folder name which actually is not recognizable by the GitHub.  here `.github` and `workflows` are folders and inside `workflows` there is another file named `linters.yml`. Please read the [documentation](https://github.com/microverseinc/linters-config/tree/master/html-css) properly.
Please update it to check linter errors automatically by Github. 
Kindly look at the below comparison table.

| Your                | Professional          |
|---------------------|-----------------------|
|   ``` Hello-Microverse-/.github/workflows ```	      |  ``` Hello-Microverse-/.github/workflows/linters.yml```                |

- I noticed that the name of the repository could be improved. It is important to have a meaningful and descriptive repository name that accurately reflects the purpose or contents of the project. Please take some time to consider changing the repository name to make it more meaningful and descriptive. Check this [document](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository) to rename it.

| Your                | Professional          |
|---------------------|-----------------------|
|   image	      |  image              |

- As per the previous reviewer's request, your branch, "feature3" does not provide sufficient clues about the changes implemented in this milestone. It is crucial to use descriptive and meaningful branch names that accurately convey the purpose and content of the changes being made.
-  Remember that your branch name should be descriptive (e.g.: refactor-authentication, user-content-cache-key, make-retina-avatars) so that others can see what is being worked on.
- As per the previous reviewer's request, you should include the `test.md` file in the `.gitignore` file as you did for the `node-modules` folder.
image

- Well done! You add a descriptive readme to your project but this has not been implemented yet, however below is a description of the major requirements for your readme file.
  - For the project requirements, kindly ensure that your README file is descriptive and professional. And the required template to be used here is the [Microverse README template](https://github.com/microverseinc/readme-template), so ensure that:
    - All main headers from the [README template](https://github.com/microverseinc/readme-template) are present in a your repo.
    - The only optional section is FAQ
    - You should delete the live demo section if you decide not to deploy the application.
    - Make sure that you have added the section Future Features, including 1-3 potential features to be added.
    - You should remove the section description, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project." should be removed and filled in with their custom content.
    - you remove the template logo. Optionally, you can replace it with your own logo you they have one.
    - No broken link or image
    - For further assistance see this [student repo for his descriptive readme](https://github.com/shahadat3669/Hello-Microverse/blob/main/README.md)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by wachirasenior0 — COMMENTED** [review]
New repository changes.

**Review by Bantealem — COMMENTED** [review]
Hi @wachirasenior0 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, the pull request is closed. I can't see your changes and it's not clear on which branch your latest commit is found. Kindly, don't open a new PR for the same project. In this case, you should submit an open pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
